# yaml-language-server: $schema=https://json.schemastore.org/prettierrc
---
printWidth: 120
tabWidth: 2
endOfLine: lf
useTabs: false
semi: false
singleQuote: true
trailingComma: none
bracketSpacing: true
arrowParens: avoid
