# yaml-language-server: $schema=https://json.schemastore.org/prettierrc
---
printWidth: 180
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: none
bracketSpacing: false
arrowParens: avoid
endOfLine: lf
