# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
---
name: Environment Variables
description: 🔠 Fetch and use deployment environment variables without hitting deployment.
author: Dariusz Porowski
branding:
  icon: dollar-sign # https://feathericons.com/
  color: gray-dark

inputs:
  # required
  github-token:
    description: GitHub token to use for API authentication
    required: true
    default: ${{ github.token }}

  environment:
    description: Deployment Environment name.
    required: true

  # optional
  repository:
    description: |
      Full repository name in the {owner}/{repo} format.
      Default: github.repository
    required: false
    default: ${{ github.repository }}

  output-to:
    description: |
      Output to...
      Supported options:
      - env: Set environment variables
      - action: Set action outputs
      - all: Set both environment variables and action outputs
      Default: all
    required: false
    default: 'all'

  env-prefix:
    description: |
      Prefix for environment variables.
      Default: not set
    required: false

  dry-run:
    description: |
      Whether or not to actually perform operation. Set to true for testing.
      Default: false
    required: false
    default: 'false'

runs:
  using: node16
  main: dist/index.js
