# yaml-language-server: $schema=https://json.schemastore.org/codecov.json
---
coverage:
  status:
    project:
      default:
        # Fail the status if coverage drops by >= 5%
        threshold: '5'
    patch:
      default:
        threshold: '5'

comment:
  layout: reach

github_checks:
  annotations: true

ignore:
  - 'tests'
