---
name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  ci:
    uses: raven-actions/.workflows/.github/workflows/__ci-testcov.yml@main
    secrets: inherit
