---
name: Dependabot

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'package-lock.json'
      - 'package.json'
      - '.github/workflows/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  dependabot:
    uses: raven-actions/.workflows/.github/workflows/__dependabot.yml@main
    secrets: inherit
