---
name: Publish Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag-name:
        description: Tag name that the major tag will point to
        required: true

jobs:
  release-publish:
    uses: raven-actions/.workflows/.github/workflows/__release-publish-action.yml@main
    secrets: inherit
    with:
      tag-name: ${{ github.event.inputs.tag-name || github.event.release.tag_name }}
