---
name: Draft Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-draft:
    uses: raven-actions/.workflows/.github/workflows/__release-draft.yml@main
    secrets: inherit
